version: '5.5.0'

services:
  postgres:
    image: postgres:latest
    container_name: dev-postgres
    environment:
      POSTGRES_DB: ${SPRING_DATABASE_NAME}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: dev-redis
    command: redis-server --requirepass ${DATA_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.3
    container_name: dev-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:9.5.3
    container_name: dev-logstash
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/drivers:/usr/share/logstash/custom_drivers
    depends_on:
      - postgres
      - elasticsearch
volumes:
  postgres_data:
  redis_data:
  es_data: