jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS} # Thời hạn Access Token: 1 phút
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS} # Thời hạn Refresh Token: 7 ngày