server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /javasecurityaudit

spring:
  application:
    name: am_islms_core

  # Cấu hình MySQL Database
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        org.hibernate.envers.audit_table_suffix: _aud

  # Cấu hình Redis Connection
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
      password: ${DATA_REDIS_PASSWORD}
      timeout: 3000ms

# Cấu hình Custom Properties cho Security JWT & Audit Stream
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

audit:
  redis-stream-key: ${AUDIT_REDIS_STREAM_KEY}
  redis-group-name: ${AUDIT_REDIS_GROUP_NAME}

login:
  attempt-max: ${LOGIN_ATTEMPT_MAX}
  block-time-minutes: ${LOGIN_BLOCK_TIME_MINUTES}
  attempt-window-minutes: ${LOGIN_ATTEMPT_WINDOW_MINUTES}