input {
  # 1. Quét bảng Users
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/custom_drivers/postgresql-42.7.11.jar"
    jdbc_driver_class => "Java::org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/javasecurityaudit"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    
    # Bật chia nhỏ dữ liệu đọc từ Postgres
    jdbc_paging_enabled => true
    jdbc_page_size => 5000
    
    schedule => "* * * * *"
    statement => "SELECT * FROM users WHERE updated_at > :sql_last_value ORDER BY updated_at, id ASC"
    
    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    
    last_run_metadata_path => "/usr/share/logstash/.logstash_jdbc_last_run_users"
    clean_run => false
    type => "user_data"
  }

  # 2. Quét bảng Invoices
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/custom_drivers/postgresql-42.7.11.jar"
    jdbc_driver_class => "Java::org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/javasecurityaudit"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    
    # Bật chia nhỏ dữ liệu đọc từ Postgres
    jdbc_paging_enabled => true
    jdbc_page_size => 5000
    
    schedule => "* * * * *"
    statement => "SELECT * FROM invoices WHERE updated_at > :sql_last_value ORDER BY updated_at, id ASC"    
    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    
    last_run_metadata_path => "/usr/share/logstash/.logstash_jdbc_last_run_invoices"
    clean_run => false
    type => "invoice_data"
  }
}

filter {
  if [type] == "user_data" {
    mutate {
      rename => {
        "full_name" => "fullName"
        "account_non_locked" => "accountNonLocked"
      }
      remove_field => ["password", "@version", "@timestamp"]
    }
  }
  
  if [type] == "invoice_data" {
    mutate {
      rename => {
        "invoice_code" => "invoiceCode"
        "customer_name" => "customerName"
        "customer_email" => "customerEmail"
        "customer_phone" => "customerPhone"
        "total_amount" => "totalAmount"
        "invoice_date" => "invoiceDate"
        "due_date" => "dueDate"
      }
      remove_field => ["@version", "@timestamp"]
    }
  }
}

output {
  if [type] == "user_data" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "users"
      document_id => "%{id}"
    }
  }

  if [type] == "invoice_data" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "invoices"
      document_id => "%{id}"
    }
  }
  
  stdout {
    codec => rubydebug
  }
}